""""
To run, follow these commands:

python run.py extract --data-dir " " --limit-per-class 300 --out feats_small.npz

then:

python run.py train --features feats_small.npz

to test on a new image, do:


"""



import argparse
import json
import sys
import time
from pathlib import Path
import os

import torch.nn as nn
from torchvision import models
import torch
from PIL import Image
from torchvision import transforms


from dotenv import load_dotenv
import numpy as np

## STAGE 2 IMPORTS
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import (StratifiedGroupKFold, StratifiedKFold,
                                     cross_val_score, train_test_split)

import joblib

env = load_dotenv()
ROOT = os.getenv("IMAGE_DIR")


CLASS_DIRS = {
    "colon_aca": "colon adenocarcinoma",
    "colon_n": "colon benign",
    "lung_aca": "lung adenocarcinoma",
    "lung_n" : "lung benign",
    "lung_scc": "lung squamos cell carcinoma",
}

IMG_EXT = {".jpeg", ".jpg", ".png", ".tif", ".tiff", ".bmp"}


AUGS_PER_ORIGINAL = 20 #images were generated by flipping and rotating the same images so its ~20 per original image


def find_class_dirs(root: Path) -> dict[str, Path]:
    found: dict[str, Path] = {}
    for path in [root, *root.rglob("*")]:
        if path.is_dir() and path.name in CLASS_DIRS and path.name not in found:
            found[path.name] = path

    missing = set(CLASS_DIRS) - set(found)
    if missing:
        raise SystemExit( f"Could not find class folder(s) {sorted(missing)} under {root}.\n"
            f"Expected subfolders named: {sorted(CLASS_DIRS)}\n"
            f"Found instead: {sorted(found) or 'nothing'}")

    return found

def index_images(root: Path, limit_per_class: int | None, seed: int):
    dirs = find_class_dirs(root)
    class_names = sorted(dirs)
    rng = np.random.default_rng(seed)

    paths: list[str] = []
    labels: list[int] = []
    for idx, name in enumerate(class_names):
        files = sorted(p for p in dirs[name].iterdir() if p.suffix.lower() in IMG_EXT)
        if not files:
            raise SystemExit(f"No images in {dirs[name]}")

        if limit_per_class and len(files) > limit_per_class:
            files = [files[i] for i in sorted(rng.choice(len(files), limit_per_class, replace=False))]
            paths += [str(p) for p in files]

            labels += [idx] * len(files)
            print(f" {name:.10s} {len(files):6d} images ({CLASS_DIRS[name]})")


    return paths, np.asarray(labels, dtype=np.int64), class_names


    ## STAGE 1: Feature Extraction


def build_backbone(name: str):

    if name == "resnet18":
        net = models.resnet18(weights = models.ResNet18_Weights.IMAGENET1K_V1)
        dim = net.fc.in_features
        net.fc = nn.Identity()
    else: 
        raise SystemExit(f"Unknown backbone name {name}!")
    net.eval()

    for p in net.parameters():
        p.requires_grad = False
    return net, dim


class ImageList(torch.utils.data.Dataset):
    def __init__(self, paths, labels, transform):
        self.paths = paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, index):
        with Image.open(self.paths[index]) as im:
            return self.transform(im.convert("RGB")), self.labels[index]


def make_dataset(paths, labels, img_size):
    tf = transforms.Compose([
        transforms.Resize(int(img_size * 1.14)),
        transforms.CenterCrop(img_size),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    return ImageList(paths, labels, tf)


def cmd_extract(args):

    torch.set_num_threads(args.threads or torch.get_num_threads())
    print(f"torch {torch.__version__} | threads = {torch.get_num_threads()}")

    print(f"\nIndexing {args.data_dir}...")

    paths, labels, class_names = index_images(Path(args.data_dir), args.limit_per_class, args.seed)

    print(f"    total {len(paths)} images, {len(class_names)} classes ")

    print(f"Loading Backbone {args.backbone} ...")
    net, dim = build_backbone(args.backbone)

    print(f"    feature dimention: {dim}")

    loader = torch.utils.data.DataLoader(
        make_dataset(paths, labels, args.img_size),
        batch_size= args.batch_size, 
        shuffle = False,
        num_workers= args.workers,
        drop_last=False,
    )

    feats = np.zeros((len(paths), dim), dtype = np.float32)
    t0 = time.time()
    done = 0

    with torch.inference_mode(): # No autograd graph -> faster
        for x, _ in loader:
            out = net(x).cpu().numpy()
            feats[done:done + len(out)] = out

            done += len(out)

            rate = done / (time.time() - t0)

            eta = (len(paths) - done) / max(rate, 1e-9)

            print(f"\r {done} / {len(paths)} {rate:5.1f} img/s eta {eta/60:4.1f} min", end="", flush=True)

    print(f"\nDone in {(time.time() - t0)/60:.1f} min")

    np.savez_compressed(
        args.out,
        features = feats,
        labels = labels,
        paths = np.asarray(paths),
        class_names = np.asarray(class_names),
        meta = json.dumps({"backbone": args.backbone, "img_size": args.img_size}),
    )

    print(f"Saved {args.out} ({Path(args.out).stat().st_size/1e6:.1f} MB)")
    print(f"\nNext: python {Path(sys.argv[0]).name} train --features {args.out}")

        ## Stage 2: Train + Evaluate Classifier

def make_classifier(C = 1.0):
    return make_pipeline(
        StandardScaler(),
        LogisticRegression(C=C, max_iter = 3000),
    )

def print_confusion(cm, class_names):
    w = max(len(n) for n in class_names)

    header = "true // pred".rjust(w)
    print("\n" + header + " " + " ".join(f"{n[:8]:>8s}" for n in class_names))
    for i, name in enumerate(class_names):
        row = " ".join(f"{v:8d}" for v in cm[i])
        print(f"{name:>{w}} {row}   ({cm[i,i] / max(cm[i].sum(), 1):.1%} recall)")

def cmd_train(args):
    d = np.load(args.features, allow_pickle=False)
    X,y = d["features"], d["labels"]
    class_names = [str(s) for s in d["class_names"]]
    meta = json.loads(str(d["meta"]))

    print(f"Features: {X.shape[0]} samples x {X.shape[1]} dims (backbone = {meta['backbone']})")
    print("Class balance: ", dict(zip(class_names, np.bincount(y).tolist())))


    # ------------------------------------------------------------- LOADED

    Xtr, Xte, ytr, yte = train_test_split(
        X, y, test_size=args.test_size, stratify=y , random_state=args.seed
    )

    clf = make_classifier(args.C)
    t0 =  time.time()
    clf.fit(Xtr, ytr)
    train_acc = accuracy_score(ytr, clf.predict(Xtr))
    test_acc  = accuracy_score(yte, clf.predict(Xte))
    print(f"\n \t Random 80/20 tts: ({time.time()-t0:.1f}s to fit)")
    print(f"train accuracy : {train_acc:.4f}")
    print(f"test accuracy : {test_acc:.4f}")
    print(f"gap     : {train_acc - test_acc:.4f} overfitting measurement")
    print(classification_report(yte, clf.predict(Xte), target_names=class_names, digits = 4))

    print_confusion(confusion_matrix(yte, clf.predict(Xte)), class_names)

    # --------------------------------------------------------------- Is the no stable or lucky split?

    cv = cross_val_score(make_classifier(args.C), X, y, cv = StratifiedKFold(
        5, shuffle=True, random_state=args.seed), n_jobs=1
    )

    print(f"\n 5-fold stratified CV {cv.round(4)} mean {cv.mean():.4f} +/- {cv.std():.4f}")

    if args.audit:
        # -------leakage audit

        print("Leakage audit: grouped split")

        groups = np.zeros(len(y), dtype = np.int64)
        next_gid = 0
        for c in np.unique(y):
            idx = np.flatnonzero(y == c)
            k = max(2, len(idx) // AUGS_PER_ORIGINAL)
            Xn = X[idx] / (np.linalg.norm(X[idx], axis=1, keepdims=True) + 1e-9)

            km = MiniBatchKMeans(
                n_clusters=k,
                random_state=args.seed,
                n_init=3,
                batch_size=1024
            )

            groups[idx] = km.fit_predict(Xn) + next_gid

            next_gid += k

            print(f"  {class_names[c]:10s} -> {k} approximate slide groups")

        min_groups = min(len(np.unique(groups[y == c])) for c in np.unique(y))

        if min_groups < 10:
            print(f"  [skipped] only {min_groups} groups in the smallest class -- the grouped", 
                  "\n   folds would be degenerate. Run this on the full dataset,",
                  "\n   or with --limit-per-class 500 or more.")
        else:
            gscores = cross_val_score(make_classifier(args.C), X, y, groups=groups, 
                                      cv = StratifiedGroupKFold(5, shuffle=True, random_state=args.seed), n_jobs = 1)
            print(f"  grouped 5-fold: {gscores.round(4)}  mean {gscores.mean():.4f}",
                f"\n  random  5-fold: mean {cv.mean():.4f}",
                f"\n optimism from near-duplicate leakage: {cv.mean() - gscores.mean():+.4f}",
                "\n ^ trust the grouped number as your real-world estimate")

        print("Learning Curve: ")

        for frac in (0.05, 0.15, 0.35, 0.65, 1.0):
            n = max(len(class_names) * 5, int(len(Xtr) * frac))
            sub = np.random.default_rng(args.seed).choice(len(Xtr),n ,replace=False)

            m = make_classifier(args.C).fit(Xtr[sub], ytr[sub])

            print(f"n={n:6d}  test acc {accuracy_score(yte, m.predict(Xte)):.4f}")


        # Sanity check

        if args.audit:
            rng = np.random.default_rng(args.seed)
            y_shuf = rng.permutation(ytr)
            m = make_classifier(args.C).fit(Xtr, y_shuf)

            print(f"\nShuffled-label control: {accuracy_score(yte, m.predict(Xte)):.4f} "
              f"(chance = {1/len(class_names):.4f}) -- if this is high, there's a bug.")


    if args.model_out:
        
        joblib.dump({"clf": clf, "class_names": class_names, "meta": meta}, args.model_out)
        print(f"\nSaved model -> {args.model_out}")



    ## Stage 3: Predict on new image

def cmd_predict(args):

    bundle = joblib.load(args.model)
    net, _ = build_backbone(bundle["meta"]["backbone"])
    ds = make_dataset([args.image], np.zeros(1, dtype = np.int64), bundle["meta"]["img_size"])

    with torch.inference_mode():
        feat = net(ds[0][0].unsqueeze(0)).cpu().numpy()

    proba = bundle["clf"].predict_proba(feat)[0]

    order = np.argsort(proba)[::-1]

    print(f"\n{Path(args.image).name}")
    for i in order:
        print(f"  {bundle['class_names'][i]:10s} {proba[i]:7.2%}  {CLASS_DIRS.get(bundle['class_names'][i], '')}")


        ##----------MAIN----------------------


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest = "cmd", required=True)

    e = sub.add_parser("extract", help="run images through the frozen backbone, cache features")

    e.add_argument("--data-dir", required=True, help="folder containing the 5 class subfolders")
    e.add_argument("--out", default="features.npz")
    e.add_argument("--backbone", default="resnet18",
                   choices=["resnet18", "resnet50", "mobilenet_v3_large"])
    e.add_argument("--img-size", type=int, default=224)
    e.add_argument("--batch-size", type=int, default=32)
    e.add_argument("--workers", type=int, default=4, help="image-loading processes; 0 if Windows complains")
    e.add_argument("--threads", type=int, default=0, help="torch CPU threads (0 = auto)")
    e.add_argument("--limit-per-class", type=int, default=None, help="use a random subset, for quick trials")
    e.add_argument("--seed", type=int, default=42)
    e.set_defaults(func=cmd_extract)

    t = sub.add_parser("train", help="fit + evaluate the classifier on cached features")
    t.add_argument("--features", default="features.npz")
    t.add_argument("--test-size", type=float, default=0.2)
    t.add_argument("--C", type=float, default=1.0, help="inverse regularisation strength")
    t.add_argument("--audit", action="store_true", help="run the leakage + sanity checks")
    t.add_argument("--model-out", default=None)
    t.add_argument("--seed", type=int, default=42)
    t.set_defaults(func=cmd_train)
 
    p = sub.add_parser("predict", help="classify a single image")
    p.add_argument("--model", required=True)
    p.add_argument("--image", required=True)
    p.set_defaults(func=cmd_predict)
 
    args = ap.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()